on:
  workflow_call:

env:
  RELEASE_NAME: "floe"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pack
        run: dotnet pack --configuration ${{ env.BUILD_CONFIGURATION }} --no-build ./nupkg

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
