name: CI

on:
  workflow_call:
    outputs:
      semver:
        value: ${{ jobs.gv-versioning.outputs.gv-semver }}

env:
  NET_SDK_VERSION: "9.0.301"
  BUILD_CONFIGURATION: "Release"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.NET_SDK_VERSION }}

      - name: Build
        run: dotnet build Floe.slnx --configuration ${{ env.BUILD_CONFIGURATION }}

  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.NET_SDK_VERSION }}

      - name: Test
        run: dotnet test Floe.slnx --no-restore --verbosity normal

  gv-versioning:
    runs-on: "ubuntu-latest"
    outputs:
      gv-semver: ${{ steps.calculate_semver.outputs.majorMinorPatch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.0.0
        with:
          versionSpec: "6.3.x"

      - name: Calculate SemVer
        id: calculate_semver
        uses: gittools/actions/gitversion/execute@v4.0.0
